name: Weekly ETL

on:
  schedule:
    - cron: '0 10 * * 5'
  workflow_dispatch:

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies with uv
        run: uv sync

      - name: Run ETL
        run: uv run main.py
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

  run-dbt:
    runs-on: ubuntu-latest
    needs: run-etl

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies with uv
        run: uv sync

      - name: Run dbt
        run: uv run dbt run --project-dir pipeline_spotify_dbt --profiles-dir pipeline_spotify_dbt
        env:
          SUPABASE_HOST: ${{ secrets.SUPABASE_HOST }}
          SUPABASE_USER: ${{ secrets.SUPABASE_USER }}
          SUPABASE_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          SUPABASE_PORT: ${{ secrets.SUPABASE_PORT }}
          SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
          SUPABASE_SCHEMA: ${{ secrets.SUPABASE_SCHEMA }}

      - name: Test dbt
        run: uv run dbt test --project-dir pipeline_spotify_dbt --profiles-dir pipeline_spotify_dbt